MODEL: 'FeatureMatching'
FEATURE_MATCHING: 'Precomputed'
POSE_SOLVER: 'EssentialMatrixMetric'
DATASET:
  ESTIMATED_DEPTH: 'prcnn'
MATCHES_FILE_PATH: '{scene_root}/correspondences_SIFT_{pairs_txt}.npz'
EMAT_RANSAC:
  PIX_THRESHOLD: 3.0
  SCALE_THRESHOLD: 0.1
  CONFIDENCE: 0.9999
