MODEL: 'PoseDiffusion'
image_size: 224

CHKPT: 'lib/models/posediffusion/chkpt/co3d_model_1.pth'

MODEL_PARAMS:
    _target_: lib.models.posediffusion.model.PoseDiffusionModel

    pose_encoding_type: absT_quaR_logFL

    IMAGE_FEATURE_EXTRACTOR: 
        _target_: lib.models.posediffusion.model.MultiScaleImageFeatureExtractor
        freeze: False

    DENOISER: 
        _target_: lib.models.posediffusion.model.Denoiser
        TRANSFORMER:
            _target_:               lib.models.posediffusion.model.TransformerEncoderWrapper
            d_model:                512
            nhead:                  4
            dim_feedforward:        1024
            num_encoder_layers:     8
            dropout:                0.1
            batch_first:            True
            norm_first:             True


    DIFFUSER:
        _target_: lib.models.posediffusion.model.GaussianDiffusion
        beta_schedule: custom

GGS:
    enable: False