MODEL: 'Regression'
ENCODER:
  TYPE: 'ResUNet'
  BLOCK_TYPE: 1
  NUM_BLOCKS: '3-3-3'
  NOT_CONCAT: False
  NUM_OUT_LAYERS: 32
AGGREGATOR:
  TYPE: 'CorrelationVolumeWarping'
  POSITION_ENCODER: True
  MAX_SCORE_CHANNEL: True
HEAD:
  TYPE: 'ProcrustesDeepResBlock'
  ADD_BASIS: True
  AVG_POOL: True
TRAINING:
  BATCH_SIZE: 12
  NUM_WORKERS: 12
  SAMPLER: 'scene_balance'
  N_SAMPLES_SCENE: 200
  SAMPLE_WITH_REPLACEMENT: True
  LR: 1e-4
  LOG_INTERVAL: 50
  VAL_INTERVAL: 0.25
  VAL_BATCHES: 200
  EPOCHS: 50
  ROT_LOSS: 'rot_angle_loss'
  TRANS_LOSS: 'trans_l1_loss'
  LAMBDA: 1.
BACKPROJECT_ANCHORS: False
DATASET:
  HEIGHT: 240
  WIDTH: 320
  MIN_OVERLAP_SCORE: 0.0

