MODEL: 'FeatureMatching'
FEATURE_MATCHING: 'Precomputed'
POSE_SOLVER: 'EssentialMatrixMetric'
DATASET:
  ESTIMATED_DEPTH: None
MATCHES_FILE_PATH: 'data/scannet_misc/correspondences_SG_scannet_test.npz'
EMAT_RANSAC:
  PIX_THRESHOLD: 2.0
  SCALE_THRESHOLD: 0.1
  CONFIDENCE: 0.9999
