MODEL: 'FeatureMatching'
FEATURE_MATCHING: 'Precomputed'
POSE_SOLVER: 'PNP'
MATCHES_FILE_PATH: 'data/scannet_misc/correspondences_SG_scannet_test.npz'
DATASET:
  ESTIMATED_DEPTH: None
PNP:
  RANSAC_ITER: 1000
  REPROJECTION_INLIER_THRESHOLD: 3
  CONFIDENCE: 0.9999
