MODEL: 'FeatureMatching'
FEATURE_MATCHING: 'SIFT'
POSE_SOLVER: 'PNP'
DATASET:
  ESTIMATED_DEPTH: 'data/scannet_misc/scannet_test_depthmaps_dpt.npz'
PNP:
  RANSAC_ITER: 1000
  REPROJECTION_INLIER_THRESHOLD: 3
  CONFIDENCE: 0.9999
SIFT:
  NUM_FEATURES: 2048
  RATIO_THRESHOLD: 0.8