MODEL: 'FeatureMatching'
FEATURE_MATCHING: 'SIFT'
POSE_SOLVER: 'EssentialMatrixMetric'
DATASET:
  ESTIMATED_DEPTH: 'data/scannet_misc/scannet_test_depthmaps_dpt.npz'
SIFT:
  NUM_FEATURES: 2048
  RATIO_THRESHOLD: 0.8
EMAT_RANSAC:
  PIX_THRESHOLD: 3.0
  SCALE_THRESHOLD: 0.1
  CONFIDENCE: 0.9999
