MODEL: 'FeatureMatching'
FEATURE_MATCHING: 'SIFT'
POSE_SOLVER: 'Procrustes'
DATASET:
  ESTIMATED_DEPTH: None
SIFT:
  NUM_FEATURES: 2048
  RATIO_THRESHOLD: 0.8
PROCRUSTES:
  MAX_CORR_DIST: 0.05 # meters
  REFINE: True
